package modelo;
// Generated 6/05/2017 11:26:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="bdinvernadero"
)
public class Administrador  implements java.io.Serializable {


     private Integer idAdmin;
     private String nomAdmin;
     private String cargoAdmin;
     private String passAdmin;

    public Administrador() {
    }

    public Administrador(String nomAdmin, String cargoAdmin, String passAdmin) {
       this.nomAdmin = nomAdmin;
       this.cargoAdmin = cargoAdmin;
       this.passAdmin = passAdmin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_admin", unique=true, nullable=false)
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }

    
    @Column(name="nom_admin", nullable=false, length=128)
    public String getNomAdmin() {
        return this.nomAdmin;
    }
    
    public void setNomAdmin(String nomAdmin) {
        this.nomAdmin = nomAdmin;
    }

    
    @Column(name="cargo_admin", nullable=false, length=128)
    public String getCargoAdmin() {
        return this.cargoAdmin;
    }
    
    public void setCargoAdmin(String cargoAdmin) {
        this.cargoAdmin = cargoAdmin;
    }

    
    @Column(name="pass_admin", nullable=false, length=10)
    public String getPassAdmin() {
        return this.passAdmin;
    }
    
    public void setPassAdmin(String passAdmin) {
        this.passAdmin = passAdmin;
    }




}


