package modelo;
// Generated 6/05/2017 11:26:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="bdinvernadero"
)
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private String nomArea;

    public Area() {
    }

    public Area(String nomArea) {
       this.nomArea = nomArea;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_area", unique=true, nullable=false)
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }

    
    @Column(name="nom_area", nullable=false, length=50)
    public String getNomArea() {
        return this.nomArea;
    }
    
    public void setNomArea(String nomArea) {
        this.nomArea = nomArea;
    }




}


