package modelo;
// Generated 6/05/2017 11:26:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Herbicida generated by hbm2java
 */
@Entity
@Table(name="herbicida"
    ,catalog="bdinvernadero"
)
public class Herbicida  implements java.io.Serializable {


     private Integer idHerbicida;
     private String nomHerbicida;
     private int cantHerbicida;
     private String presentacionHer;

    public Herbicida() {
    }

    public Herbicida(String nomHerbicida, int cantHerbicida, String presentacionHer) {
       this.nomHerbicida = nomHerbicida;
       this.cantHerbicida = cantHerbicida;
       this.presentacionHer = presentacionHer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_herbicida", unique=true, nullable=false)
    public Integer getIdHerbicida() {
        return this.idHerbicida;
    }
    
    public void setIdHerbicida(Integer idHerbicida) {
        this.idHerbicida = idHerbicida;
    }

    
    @Column(name="nom_herbicida", nullable=false, length=50)
    public String getNomHerbicida() {
        return this.nomHerbicida;
    }
    
    public void setNomHerbicida(String nomHerbicida) {
        this.nomHerbicida = nomHerbicida;
    }

    
    @Column(name="cant_herbicida", nullable=false)
    public int getCantHerbicida() {
        return this.cantHerbicida;
    }
    
    public void setCantHerbicida(int cantHerbicida) {
        this.cantHerbicida = cantHerbicida;
    }

    
    @Column(name="presentacion_her", nullable=false, length=50)
    public String getPresentacionHer() {
        return this.presentacionHer;
    }
    
    public void setPresentacionHer(String presentacionHer) {
        this.presentacionHer = presentacionHer;
    }




}


