package modelo;
// Generated 6/05/2017 11:26:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Insecticida generated by hbm2java
 */
@Entity
@Table(name="insecticida"
    ,catalog="bdinvernadero"
)
public class Insecticida  implements java.io.Serializable {


     private Integer idInsecticida;
     private String nomInsecticida;
     private int cantInsecticida;
     private String presentacionInsec;

    public Insecticida() {
    }

    public Insecticida(String nomInsecticida, int cantInsecticida, String presentacionInsec) {
       this.nomInsecticida = nomInsecticida;
       this.cantInsecticida = cantInsecticida;
       this.presentacionInsec = presentacionInsec;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_insecticida", unique=true, nullable=false)
    public Integer getIdInsecticida() {
        return this.idInsecticida;
    }
    
    public void setIdInsecticida(Integer idInsecticida) {
        this.idInsecticida = idInsecticida;
    }

    
    @Column(name="nom_insecticida", nullable=false, length=50)
    public String getNomInsecticida() {
        return this.nomInsecticida;
    }
    
    public void setNomInsecticida(String nomInsecticida) {
        this.nomInsecticida = nomInsecticida;
    }

    
    @Column(name="cant_insecticida", nullable=false)
    public int getCantInsecticida() {
        return this.cantInsecticida;
    }
    
    public void setCantInsecticida(int cantInsecticida) {
        this.cantInsecticida = cantInsecticida;
    }

    
    @Column(name="presentacion_insec", nullable=false, length=50)
    public String getPresentacionInsec() {
        return this.presentacionInsec;
    }
    
    public void setPresentacionInsec(String presentacionInsec) {
        this.presentacionInsec = presentacionInsec;
    }




}


