package modelo;
// Generated 6/05/2017 11:26:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Planta generated by hbm2java
 */
@Entity
@Table(name="planta"
    ,catalog="bdinvernadero"
    , uniqueConstraints = @UniqueConstraint(columnNames="nom_planta") 
)
public class Planta  implements java.io.Serializable {


     private Integer idPlanta;
     private String nomPlanta;
     private String descripcionPlanta;
     private byte[] imagenPlanta;
     private Date fechaCultivo;

    public Planta() {
    }

    public Planta(String nomPlanta, String descripcionPlanta, byte[] imagenPlanta, Date fechaCultivo) {
       this.nomPlanta = nomPlanta;
       this.descripcionPlanta = descripcionPlanta;
       this.imagenPlanta = imagenPlanta;
       this.fechaCultivo = fechaCultivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_planta", unique=true, nullable=false)
    public Integer getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(Integer idPlanta) {
        this.idPlanta = idPlanta;
    }

    
    @Column(name="nom_planta", unique=true, nullable=false, length=50)
    public String getNomPlanta() {
        return this.nomPlanta;
    }
    
    public void setNomPlanta(String nomPlanta) {
        this.nomPlanta = nomPlanta;
    }

    
    @Column(name="descripcion_planta", nullable=false, length=250)
    public String getDescripcionPlanta() {
        return this.descripcionPlanta;
    }
    
    public void setDescripcionPlanta(String descripcionPlanta) {
        this.descripcionPlanta = descripcionPlanta;
    }

    
    @Column(name="imagen_planta", nullable=false)
    public byte[] getImagenPlanta() {
        return this.imagenPlanta;
    }
    
    public void setImagenPlanta(byte[] imagenPlanta) {
        this.imagenPlanta = imagenPlanta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_cultivo", nullable=false, length=10)
    public Date getFechaCultivo() {
        return this.fechaCultivo;
    }
    
    public void setFechaCultivo(Date fechaCultivo) {
        this.fechaCultivo = fechaCultivo;
    }




}


