package modelo;
// Generated 6/05/2017 11:26:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="bdinvernadero"
    , uniqueConstraints = @UniqueConstraint(columnNames="clave_usuario") 
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nomUsuario;
     private String claveUsuario;
     private String passUsuario;
     private String actividad;

    public Usuario() {
    }

    public Usuario(String nomUsuario, String claveUsuario, String passUsuario, String actividad) {
       this.nomUsuario = nomUsuario;
       this.claveUsuario = claveUsuario;
       this.passUsuario = passUsuario;
       this.actividad = actividad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nom_usuario", nullable=false, length=128)
    public String getNomUsuario() {
        return this.nomUsuario;
    }
    
    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }

    
    @Column(name="clave_usuario", unique=true, nullable=false, length=10)
    public String getClaveUsuario() {
        return this.claveUsuario;
    }
    
    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }

    
    @Column(name="pass_usuario", nullable=false, length=10)
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }

    
    @Column(name="actividad", nullable=false, length=250)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }




}


